[shell]
disabled = false
fish_indicator = "ğŸŸ"
bash_indicator = "ğŸ‘Š"
zsh_indicator = "ğŸ§™"

[kubernetes]
disabled = false
format = 'k8s [â›µ$context( \($namespace\))](dimmed green) '
[kubernetes.context_aliases]
"kind-kind" = "local"

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '

[helm]
disabled = true

[terraform]
disabled = true

[status]
style = "bg:blue"
symbol = "ğŸ”´"
format = '[\[$symbol $status_common_meaning$status_signal_name$status_maybe_int\]]($style) '
map_symbol = true
disabled = false

[gcloud]
disabled = true

[aws]
disabled = true
